[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MartianMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MartianMono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Buttonless"
dynamic_padding = false
startup_mode = "Maximized"
option_as_alt = "Both"
opacity = 0.95
padding = { x = 2, y = 2 }

